WHITESPACE = _{ (" " | "\t" | "\n")+ }

identifier = @{('a' .. 'z' | 'A' .. 'Z' | "$") ~ (ASCII_ALPHANUMERIC | "_")* }

integer = @{('0'..'9')+}

float_constant = @{"-"? ~ integer ~ ("." ~ integer)?}

boolean_constant = {"true" | "false"}

program = {
    SOI ~
    function_call* ~
    EOI
}

function_call = {
    identifier ~ "(" ~ argument_list? ~ ")" ~ block |
    identifier ~ "(" ~ argument_list? ~ ")" ~ ";"
}

block = {
    "{" ~
    function_call* ~
    "}"
}

argument_list = {
    argument ~ ("," ~ argument)* ~ ","?
}

argument = {
    identifier ~ "=" ~ float_constant |
    identifier ~ "=" ~ boolean_constant |
    matrix
}

matrix = {
    "[" ~ matrix_rows ~ "]"
}

matrix_rows = {
    matrix_row ~ ("," ~ matrix_row)* ~ ","?
}

matrix_row = {
    "[" ~ matrix_numbers ~ "]"
}

matrix_numbers = {
    float_constant ~ ("," ~ float_constant)* ~ ","?
}
